### PR TITLE
Sync atoms

### PR DESCRIPTION
**Pull request by BoukeHaarsma23**
Wondering if we need to make the color managment one a bit more clever since we don't want it on handhelds which don't support it.

### CODE REVIEW

**Comment by BoukeHaarsma23** [comment]
This would fix https://github.com/ChimeraOS/chimeraos/issues/698

**Comment by ibanezbass** [comment]
You could also add STEAM_GAMESCOPE_COLOR_TOYS=1 in there.

**Comment by BoukeHaarsma23** [comment]
> You could also add STEAM_GAMESCOPE_COLOR_TOYS=1 in there.

That is already in there by default

**Comment by ibanezbass** [comment]
> 

Apologies, I saw that after I posted it.

**Comment by ruineka** [comment]
I created a ticket regarding some of the HDR woes to see if we get any feedback.
 https://github.com/ValveSoftware/gamescope/issues/924

**Comment by kzkzkzkzkzk** [comment]
Is it possible to change the vrr range?

**Pull request closed without merging**
