### PR TITLE
Update device-quirks for GPD win 3

### PR DESCRIPTION
**Pull request by MarkTseng**
fixed GPD win 3  orientation issue

### CODE REVIEW

**Comment by MarkTseng** [comment]
fixed GPD win 3 orientation issue

**Comment by MarkTseng** [comment]
fixed GPD win 3 orientation issue

**Comment by MarkTseng** [comment]
Please help review GPD win 3 issue

**Comment by ruineka** [comment]
It was set to normal to prevent crashing because it would crash when rotated 90 or 270 degrees. Is this no longer an issue anymore?

**Comment by MarkTseng** [comment]
Acutally, I have test on my GPD win 3 (i7-1195G7) . If I set normal mode , It shows vertical screen.
The  orientation  should be set 'right'  to fixed screen rotation issue.

**Comment by MarkTseng** [comment]
> It was set to normal to prevent crashing because it would crash when rotated 90 or 270 degrees. Is this no longer an issue anymore?

In my test, it can play game normally without crash.

**Comment by KyleGospo** [comment]
Independent report of this working from a user on our discord as well

**Comment by pastaq** [comment]
rebased and merged in #84

**Pull request closed without merging**
