### PR TITLE
Swap wayland environment variables in place with X11 ones

### PR DESCRIPTION
**Pull request by ghost**
Tested running KDE Plasma 5.27.6 on Wayland via Gentoo Linux

Fixes X11 environment variables in place of wayland environment variables, this ensures non-steam games run within gamescope and not elsewhere outside the compositor; KDE Plasma, Gnome.

For example, `/usr/bin/kodi --windowing=x11` added as a non-steam game would run in X11 on my desktop instead rather then inside gamescope.

### CODE REVIEW

**Comment by ghost** [comment]
Also includes a temporary fix for the cursor. I can't for some reason see my cursor without it.

**Comment by ghost** [comment]
I noticed with my system in particular, that I needed to use `export-gpu`. 
Without using the program, the envvars I replaced e207892, do not make a difference. 
Perhaps force export-gpu by default? I can make a seperate fork if you would like me to restrict that.

**Comment by alkazar** [comment]
I don't understand the problem description. How can a game run outside the gamescope session when it is the only session running?

**Comment by ghost** [comment]
@alkazar These fixes are for running the gamescope-session script inside a desktop environment like KDE or Gnome just like how the Steam Deck itself runs gamescope under KDE. 

I'm unsure why these variables aren't set when gamescope itself is ran. It makes me wonder whether there is a problem with the current script or whether this is a gamescope problem...

But, what I DO know is that the Steam Deck works without fault and doesn't have this issue...

As for your concerns for running the gamescope-session standalone (without a DE), these variables and parameters aren't going to cause problems. 

This PR Just ensures that where-ever the script is ran, the applications are ran using the X11 protocol instead of the unsupported Wayland protocol.

**Comment by alkazar** [comment]
It doesn't make sense to run gamescope-session under KDE or any other session. It is intended to run standalone. I don't understand how or why you are doing this. If you want to use gamescope just use it directly.

Steam Deck does not use gamescope in the desktop session.

**Pull request closed without merging**
