### PR TITLE
use device quirks script to add/remove nvidia gpu support

### PR DESCRIPTION
**Pull request by alkazar**

### CODE REVIEW

**Review by npaladin2000 — APPROVED** [review]

**Comment by Samsagax** [comment]
LGTM!

What does the called script do?

**Comment by alkazar** [comment]
> LGTM!
> 
> What does the called script do?

Adds or removes the Nvidia icd to `/etc/vulkan/icd.d`

**Review by Samsagax — APPROVED** [review]

**Comment by mustafa-archived** [comment]
@Samsagax so does this mean steam deck big picture can now run with gamescope-session on nvidia?

**Comment by Samsagax** [comment]
> @Samsagax so does this mean steam deck big picture can now run with gamescope-session on nvidia?

It does work on Nvidia. That has been the case for a while now. Well "works": you will see the client on screen. The performance will be terrible. Not suitable for daily driving.

**Comment by ruineka** [comment]
> > @Samsagax so does this mean steam deck big picture can now run with gamescope-session on nvidia?
> 
> It does work on Nvidia. That has been the case for a while now. Well "works": you will see the client on screen. The performance will be terrible. Not suitable for daily driving.

That's not entirely accurate. In a lot of cases it flat out doesn't work. At best it *can* work but with a bunch of issues.

**Comment by mustafa-archived** [comment]
> > @Samsagax so does this mean steam deck big picture can now run with gamescope-session on nvidia?
> 
> It does work on Nvidia. That has been the case for a while now. Well "works": you will see the client on screen. The performance will be terrible. Not suitable for daily driving.

ah I see, last time I checked you could only reach the steam deck's big picture on nvidia without being able to play games, starting any game would just crash the session

**Pull request merged**
